### ISSUE TITLE
Waiting for Code

### ISSUE THREAD

**Issue by IqraNosheen786** [Wenlve-Zhou/Guidance-Training#1]
Hi can u please release the code for training model with semantic guidance

**Comment by Wenlve-Zhou** [comment]
Thank you very much for your concern! Recently, we are still exploring how to apply our algorithm to Segformer more effectively, and thus it hasn't been made open source yet. Given your interest in this project, you can keep an eye on it. We will disclose our training code and configuration files on DeepLab before the end of September.

**Comment by Wenlve-Zhou** [comment]
Hi, thanks a lot for your interest in our project. We have open sourced the Deeplab-based Guidance Training code and made a note about it.
